index.html
as seen running here:
https://ipfs.macholibre.org/ipfs/QmdRmBufs6JaMaaCVJRpqxoCuhB6eJsNp8DLtaZA7Xn8gh/
=> add ipfs.macholibre.org

index.html
demo: https://ipfs.works/ipfs/Qmbcbi6fUgRFXfCkn6L2qwN8UfUerKTzRKRrhRvduddtXa/
=> add two more gateways

gateways.json
demo: https://ipfs.works/ipfs/QmetNvpZavqzNtHGGmK1MRSL9iVp3SSiXmmdz16YDJKN9N/
=> fix eternum.io, add wisdom.sh

README.md
=> add link to cli in readme

gateways.json
- https://www.cloudflare.com/distributed-web-gateway/
:rocket:  :sparkles:
=> Add cloudflare-ipfs.com

gateways.json
Add the gateway `ipfs.netw0rk.io` to the list of gateways in the json file.
=> Add ipfs.netw0rk.io to Gateway List

gateways.json
From https://guifi.net/node/102135
Will only be accessible if you're accessing it from within the Guifi
Network
License: MIT
Signed-off-by: Victor Bjelkholm <git@victor.earth>
=> Add Guifi Gateway

gateways.json
Added the official gateway for the pinata.cloud IPFS pinning service.
=> Added pinata.cloud gateway

app.js
=> Adding link to online gateway

gateways.json
=> Added jorropo.ovh

gateways.json
[`https://ipfs.fooock.com/ipfs/Qmaisz6NMhDB51cCvNWa1GMS7LU1pAxdF4Ld6Ft9kZEP2a`](https://ipfs.fooock.com/ipfs/Qmaisz6NMhDB51cCvNWa1GMS7LU1pAxdF4Ld6Ft9kZEP2a)
=> Add link to ipfs.fooock.com gateway

gateways.json
https://cdn.cwinfo.net/ipfs/Qmaisz6NMhDB51cCvNWa1GMS7LU1pAxdF4Ld6Ft9kZEP2a
=>  Add link to cdn.cwinfo.net gateway

gateways.json
I'm removing my gateway as it will be not online from the next few hours
=> Removing deo.moe gateway

gateways.json
https://ipfs.privacytools.io/ipfs/Qmaisz6NMhDB51cCvNWa1GMS7LU1pAxdF4Ld6Ft9kZEP2a
=> Add ipfs.privacytools.io

gateways.json
I recently created my own public ipfs gateway at best-practice.se
=> Add best-practice gateway

app.js, index.html
Plus some code refactor, hopefully preparing things to make it grow
Next PR: explanatory comments
test it :
https://pulsartronic.com/public-gateway-checker/
=> added CORS functionality

app.js
This mother f*cker PR is never going to be merged ... go ahead, lets add a gateway with CORS disabled and CORB enabled so we see it DOWN no matter what :kissing:
=> Preventing CORB + some explanatory comments

gateways.json
Hi,
this is my own (now public) instance.
I use this server for a number of (non stressing) things.  
I plan to keep the IPFS server running which is in a docker behind an nginx server.
=> Add ipfs.cosmos-ink.net

gateways.json
See post-merge commit on @LinusCDE's fork ... easier just to do it this way 😊 
ref https://github.com/LinusCDE/public-gateway-checker/commit/cd5deef39c2fb7aef05784836fa2463c1f143b2f
=> Amended cosmos-ink.net

gateways.json
=> Added Public Active Gateway

gateways.json
=> Fixed error in overpi's gateway link

gateways.json
Two new gateways have been added
=> add new gateway 

gateways.json
=> Add ipfs.jacl.tech

gateways.json
It has been interesting running an IPFS gateway.
Server is to be reïnstalled with a newer distro release. Will I re-add it? Who knows.
=> Remove ipfs.jeroendeneef.com as a gateway.

gateways.json
=> feat: added jorropo.net

gateways.json
Geo: Canada, Montreal
Speed: 1Gbps
Space: 5TB
=> feat: add gw.ipfspin.com

gateways.json
Geographic Location: India
Connection speed: 200mbps
Available Space: default (9GB?)
=> feat: add ipfs.kavin.rocks

gateways.json
* Gateway URL: https://ipfs.mihir.ch/ipfs/:hash
* Geographic location: India
=> feat: add ipfs.mihir.ch

gateways.json
Adding a gateway hosted in a small VPC in the US.
=> feat: add astyanax.io

gateways.json
=> feat: add crustwebsites.net

gateways.json
=> added gateways

gateways.json
=> feat: add ipfs.taxi

gateways.json
Scala IPFS Gateway: Netherlands, 1Gbit/s, 200 GB
=> feat: add https://ipfs.scalaproject.io/

README.md, app.js
Per https://github.com/ipfs/public-gateway-checker/issues/149, change ✅ to 🌍 for less "OK" vibes and more "online" ones.
Closes https://github.com/ipfs/public-gateway-checker/issues/149.
=> change ✅ to 🌍

app.js
This PR makes the Origin check more strict: after confirming subdomains work, additional request for path is made, to confirm legacy paths are redirected to expected subdomains.
Adding this test is necessary, because there are misconfigured gateways that don't redirect /ipfs/{cid} paths to {cid}.ipfs.example.com  subdomains and return data from the root origin, effectively defeating any Origin isolation provided by subdomains. :see_no_evil: 
This fix will incentivize gateway operators to fix such misconfigurations + inform users about real risks.
cc @schomatis fyi an example of misconfigured gateway: 
- subdomain "works" (is naively redirected to dweb.link for some reason): https://bafybeifx7yeb55armcsxwwitkymga5xf53dxiarykms3ygqic223w5sk3m.ipfs.ipfs.drink.cafe/#x-ipfs-companion-no-redirec …
=> fix(origin): confirm paths redirect to subdomain

gateways.json
=> Add Storry.TV

gateways.json
=> feat: add ipfs.kxv.io public IPFS gateway

gateways.json
I'm the owner of ipfs.forsla.app and i've shut it down permanently.
=> remove ipfs.forsla.app

gateways.json
Added `dweb.eu.org` and `permaweb.eu.org`
=> Add new gateway

gateways.json
=> Remove ipfs.1-2.dev

src/index.html
=> fix: origin typo

src/gateways.json
=> feat: add tth-ipfs.com gateway

src/gateways.json
removing ipfs-zod.tv.
We are closing up shop, do not want this to linger, thanks!
=> feat: remove ipfs-zod.tv

src/gateways.json
=> feat: add 4everland.io gateway

src/gateways.json
Provided by https://web3.storage/products/w3link/
=> feat: add w3s.link gateway

src/gateways.json
Geographic Location: Serbia
Connection Speed: 700/70 Mbps
Available Space: 100Gb
=> feat: add cthd.icu

package-lock.json, package.json
=> fix: npm start should work without prior cmds

src/gateways.json
=> feat: new gateway https://ipfs.tayfundogdas.me/ipfs

src/gateways.json
In this PR, I'm:
ADDING A NEW PUBLIC GATEWAY:
- geographic location: Calgary, AB, Canada 🇨🇦 
- connection speed: https://www.speedtest.net/result/c/67955ae6-e179-4e6b-8e19-63d71ae32209
- available space: 350gb
=> feat: add ipfs.pinksheep.whizzzkid.dev

src/gateways.json
Hi,
Take me for a mate!
geographic location: Japan
connection speed: 100Mbps
available space: 10GB
=> feat: add ipfs.jpu.jp

src/gateways.json
Starbase is a decentralized IPFS gateway service, operating as a collective of IPFS kubo nodes from around the world. We are committed to the principles of decentralization, allowing third-party nodes to join and contribute to our gateway. Our aim is to provide a user-friendly interface for seamless interaction with the IPFS network.
This gateway is part of our commitment to our IPFS open grants:  https://github.com/ipfs/devgrants/blob/master/open-grants/open-proposal-distributed-pinning-protocol.md
Website: https://www.gw3.io/
=> feat: add starbase.gw3.io

src/gateways.json
France, 10Gb/s, 2 servers  load balanced
=> feat: add getipfs.com

package-lock.json, package.json
- chore(deps): ncu -u && npm i
- chore(deps): npm audit fix
=> chore(deps): update deps and npm audit fix

package-lock.json, package.json
ipfs & ipfs-http-client are not used
resolves #406 & #407
=> fix: remove ipfs and ipfs-http-client deps

src/gateways.ts
=> fix: remove red-page ipns.co

src/gateways.ts
This is a dedicated gateway from web3ph group from Philippines. 
The server is located in Singapore.
=> feat: add storage.web3ph.dev

gateways.json
dweb.eu.org redirects to cloudflare:
```
$ http https://dweb.eu.org/ipfs/bafybeicklkqcnlvtiscr2hzkubjwnwjinvskffn4xorqeduft3wq7vm5u4
HTTP/1.1 302 Moved Temporarily
CF-RAY: 859f709e0cb8437f-EWR
Cache-Control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection: keep-alive
Date: Fri, 23 Feb 2024 12:23:25 GMT
Expires: Thu, 01 Jan 1970 00:00:01 GMT
Location: https://cloudflare-ipfs.com/ipfs/bafybeicklkqcnlvtiscr2hzkubjwnwjinvskffn4xorqeduft3wq7vm5u4
NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=lRUEOrOzL%2Bibn%2FqISgpNhr40KYaXUZHDtJoMj71m1Hj%2FZIXW2o7bjmIarglnSivrRkKzdUMGl7XRgDvkAiY%2BpVkK3FbCnhyKrNH%2F%2BlLglYXb2FRMGFtFh3kCxp8qjQ%3D%3D"}],"group":"cf-nel" …
```
=> chore: remove dweb and fleek

gateways.json
Please add a new public ipfs gateway - https://dlunar.net
This gateway is globally distributed and uses Gcore CDN to cache and deliver files
=> feat: dlunar.net

gateways.json
Fleek announced they will be running a Public Gateway for some time:
https://fleek.xyz/blog/announcements/fleek-decentralized-ipfs-gateway/
> Today we are releasing a V0 of the gateway, which is a highly performant, regionally distributed, traditional public IPFS gateway
=> feat: add flk-ipfs.io

gateways.json
Add a new USA location public gateway https://dwt.my.id
=> feat: add dwt.my.id

gateways.json
Fleek announced they will be running a Public Gateway for some time:
https://fleek.xyz/blog/announcements/fleek-decentralized-ipfs-gateway/
The domain for this gateway has been updated and should be updated in this list
=> feat: add flk-ipfs.xyz

package-lock.json, package.json, src/index.html
https://github.com/ipfs-shipyard/ipfs-geoip/releases/tag/v9.2.0
=> chore: ipfs-geoip v9.2.0
