ipfs/public-gateway-checker

app.js
[Our browser extension](https://github.com/ipfs/ipfs-companion) redirects request to gateways, which breaks this status page. Additionally, due to a [workaround](https://github.com/ipfs-shipyard/ipfs-companion/pull/494) for [CORS bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1450965)  it  produces [different results under Chrome and Firefox](https://user-images.githubusercontent.com/157609/41968786-afd51498-7a05-11e8-9941-130034ceb29f.png).
**TL;DR** we don't want browser extension to touch requests made by public-gateway-checker
This PR  adds an explicit opt-out hint that ensures test requests reach the right gateway.
More info about opt-out URL hint: https://github.com/ipfs-shipyard/ipfs-companion/pull/505 
(to be released with next version of browser extension)
cc …
=> Opt-out from gateway redirects done by IPFS Companion

gateways.json
Just adds another public IPFS gateway to the list. This gateway is hosted on a good connection, and should be useful to the community. =)
=> Add ipfs.greyh.at to gateways.json

gateways.json
Test plan: https://rawgit.com/burdakovd/public-gateway-checker/c27602cbfc6b99deda97f323789b1cb708001392/
More info about the gateway at dapps.earth
Key feature: content is served from subdomains for better origin-based isolation, e.g. https://ipfs.dapps.earth/ipfs/Qmaisz6NMhDB51cCvNWa1GMS7LU1pAxdF4Ld6Ft9kZEP2a is redirected to https://bafybeifx7yeb55armcsxwwitkymga5xf53dxiarykms3ygqic223w5sk3m.ipfs.dapps.earth/
=> Add gateway at ipfs.dapps.earth

README.md, app.js, gateways.json
This PR adds:
- status next to each gateway to highlight which gateways provide Origin isolation 
- two known public gateways that support [CID in Subdomain](https://docs.ipfs.io/guides/guides/addressing/#subdomain-gateway)
Preview:
[![screenshot_2019-12-14.png](https://ipfs.io/ipfs/QmX53EdPJxH377WHfwH8wV3tu8Zzjq9ojgQS6U82JRM6bd?filename=screenshot_2019-12-14.png)](https://ipfs.github.io/public-gateway-checker/)
cc @autonome, https://github.com/ipfs/ipfs/issues/337, https://github.com/ipfs/in-web-browsers/issues/89, https://github.com/ipfs/go-ipfs/issues/6498
=> feat: add public subdomain gateways and Origin check

README.md, app.js, index.html, publish-to-ipfs.sh, styles.css
Just changed its look a little bit based on @fsdiogo 's work ... related to #79 
test it: https://lazyweirdo.github.io/public-gateway-checker/
In reference to ipfs/ipfs-gui#80 ... preparing things for
@olizilla
> Allow folks to submit new gateways via a PR in Github, including gateway url, Contact email, Developer or Company name and logo - to celebrate those offering public infrastructure)
> Clearly Link to it or incorporate the information into the main https://ipfs.io wesite along with links to information about how to run your own
> Create a map visualization of where are all the IPFS Gateways in the World.
@alanshaw 
> Things I'd also like to know status of:
> - Preload nodes
> - Public WebRTC and Websocket star rendezvous servers
Last one i don't know if it is still needed because …
=> Nicer look

README.md, app.js, index.html, lastpubver, styles.css
Various UX tweaks on top of #83 by @lazyweirdo: 
- added link to github repo in the right corner (https://github.com/tholman/github-corners)
- switched to colors and fonts from https://github.com/ipfs-shipyard/ipfs-css
- I did not rewrite entire thing to use tachyons to keep this PR small
- same font size in all columns (fixes [this bug](https://user-images.githubusercontent.com/157609/71595476-2232ad00-2b3c-11ea-8f95-511af4fe28a2.png))
- improved links about CORS and Origin tests
- removed `.ipfs.` from displayed hostnames of subdomain gateways
- long hostnames get truncated on narrow screens without breaking layout ([demo](https://user-images.githubusercontent.com/157609/71595837-7e4a0100-2b3d-11ea-8511-9d69219717cd.png))
- README: added note how to test locally:
```
$ npx http-server . …
```
=> UX improvements

gateways.json
So... I don't actually know if https://storjipfs-gateway.com/ is supposed to be a permanent thing.. but it's out there. When you upload something to https://storjipfs.com/ it links to your upload on that gateway.
=> Add storjipfs-gateway.com

gateways.json
Replaced ipfs.stibarc.gq (defunct) with ipfs.stibarc.com (active)
=> Update outdated gateway URL to new one

index.html, styles.css
Ref https://github.com/ipfs-shipyard/ipld-explorer/pull/57#pullrequestreview-421960888: Clones visual style of GitHub link from IPLD Explorer. Also removes some CSS rendered extraneous by use of tachyons.
=> Header from IPLD Explorer; removes css extraneous to tachyons

gateways.json
It is not intended to function as an IPFS gateway.
=> remove filecoin.io as a gateway

index.html
Details about geoip update: https://github.com/ipfs-shipyard/ipfs-geoip/pull/80
=> feat: update geoip dataset (2020-10-13)

.github/pull_request_template.md, README.md
Closes #47 by the following:
- adds PR template
- Clarifies gateway submission process in README.md
=> docs: improve submission/PR info

gateways.json
it is hosted as an azure appservice westus2 it has quite fast internet connection and 10gb of cache
=> feat: add add ipfs.azurewebsites.net

gateways.json
Added https://ipfs.denarius.io Public IPFS Gateway.
More information: https://denarius.io/ipfs
=> Update Gateways to include Denarius IPFS Gateway

gateways.json
The jes.xxx domain is too expensive to keep renewing so I'll be getting rid of it in time.
(If anyone wants to buy it please let me know!).
=> Remove jes.xxx gateway

gateways.json
- VPS hosted on Vultr Singapore
- IPFS server 0.8.0-rc1
- GO 1.15.6
- 15Gb space
- Subdomain gateway support
- CORS free
=> feat: add bluelight.link

gateways.json
I changed the gateway address to a subdomain name some time ago, and it is now online again.
The server is located in France, a gigabit network, and the cache limit is set to 1TB. and use cloudflare gateway to distribute data.
=> Update gateway domain

gateways.json
server is located in Mumbai India, its a ubuntu 20.04 server, **ipfs.noormohammed.tech** is proxyed by **cloudflare** free tier.
network bandwidth is Download: 103.57 Mbit/s, Upload: 0.85 Mbit/s
bandwidth is checked by `curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -`
=> feat: add ipfs.noormohammed.tech

gateways.json
1. geographic location
- Country name: South Korea
- Flag image CID:  QmfQHWvbxvbfLDNvNXF259EARbtbWQwLgbXcMFqDZW39Xz
2. connection speed
- 99ms
3. available space
- It is 1000GB based on garbage collector, but it is expandable because we use AWS S3.
=> eat: add gateway.address.here

gateways.json
This gateway is a ubuntu 18.04 server located in Hongkong, with 400GB SSD disk space.
_https://ipfs.decoo.io_ is proxyed and protected by Cloudflare.
The network bandwidth is _Download: 95.17 Mbit/s, Upload: 4.17 Mbit/s_ (tested by speedtest).
=> feat: add decoo.io

gateways.json
I'm not too sure about the policy on PRs of *removing* gateways, but here's the motive:
`smartsignature.io` appears to no longer exist, instead landing on a park page. It appears though that the people behind said park page are also responding to all `.js` file requests with the following:
```js
if (typeof _popwnd == 'undefined') {
var _popwnd = -1;
function _popwnd_open(){
if (_popwnd!=-1) return;
_popwnd = window.open('http://iyfnz.com/?dn=smartsignature.io&pid=9PO755G95', '_blank', '');
_popwnd.blur();
window.focus();
}
};
window.addEventListener('click', _popwnd_open);
```
The `ipfs.smartsignature.io` domain is also affected by this.
As the gateway checker loads JS from these gateways in order to test them, the checker is unintentionally loading this script, causing a new tab to be …
=> feat: remove smartsignature.io

gateways.json
Node is based in Canada 1/1G speed. Will be part of a larger cluster shortly, adding France and Italy 🇮🇹
=> feat: add ipfs.ivoputzer.xyz

README.md, app.js, gateways.json, index.html, styles.css
This cosmetic  PR:
- simplifies online, cors and origin checks as much as one could have given the _organically grown_ code in app.js :sweat_smile:
- loading JS is more often blocked than  `<img>`, so this  closes #118
-  adds a **security disclaimer** regarding gateways that do not provide Origin isolation.
> ![Screen Shot 2021-06-08 at 02 42 06](https://user-images.githubusercontent.com/157609/121105402-58ca2800-c804-11eb-951a-c570e76a9b21.png)
cc @autonome @momack2 @ribasushi @gmasgras  @mburns  @aschmahmann @jessicaschilling   – lmk if we should tweak messaging or the way check results are presented.
When we are happy with this PR  I'll ping relevant gateway operators to nudge migration to subdomains before https://github.com/ipfs/in-web-browsers/issues/157 ships in  go-ipfs 0.10+.
=> feat: improved origin isolation check

gateways.json
Fixes #147. To simplify URLs with origin isolation https://ipfs.ivoputzer.xyz has been moved to https://ivoputzer.xyz and redirect will be dropped shortly. Thanks 😄
=> fix: update ipfs.ivoputzer.xyz gateway entry

README.md, index.html, styles.css
Adds SECURITY NOTES to  README based on changes from #148 + mirrors them at the top of checker, so its hard to ignore:
cc @autonome @momack2 @ribasushi @gmasgras @mburns @aschmahmann @jessicaschilling @schomatis
lmk SECURITY NOTES section could be improved
=> docs: improved security notes

gateways.json
Hello! I am the owner and operator of ipfs.foxgirl.dev ([proof](https://ipfs.foxgirl.dev/whoami)).
I'd like to have my gateway removed from the public gateway checker, my network simply cannot keep up with the amount of external traffic I've been getting since my gateway was added to the gateway checker listing in #138. I'm going to keep ipfs.foxgirl.dev up (potentially redirecting to a different public gateway) but I'm going to move everything over to a properly private gateway soon.
Also, I'd appreciate if requests to add any new *.foxgirl.dev gateways to the gateway checker be denied, but I know how annoying it can be to maintain a OSS project, so don't worry about it too much.
Thanks, and have a great night! (or whatever time it is where you are :3)
=> feat: remove ipfs.foxgirl.dev

gateways.json
Removing https://trusted-setup.filecoin.io from the list of gateways because:
> @gmasgras that's the collab cluster which should not be used as a gateway
=> fix: remove trusted-setup.filecoin.io from gateway list

gateways.json
Added no-subdomain version of ipfs.stibarc.com, ipfs-nosub.stibarc.com, in case a client didn’t want subdomains and just a regular link
=> feat: add ipfs-nosub.stibarc.com

gateways.json
=> feat: add ipfs.1-2.dev

gateways.json
ipfs.namebase.io is an IPFS gateway created by Namebase that anyone can use to connect their decentralized Handshake domain to their IPFS stuff.
=> feat: add ipfs.namebase.io

gateways.json
Hello,
I am adding my public gateway. Its hosted in Turkey/Istanbul. I have 100mbit/s unlimited bandwidth connection and hooked 4TB drives in RAID 1 mode. I believe this can be a small contribution to people in Turkey like me running their websites on ipfs. I would be happy if you add my public gateway to the list.
=> feat: add ipfs.kinematiks.com

gateways.json
Finland, Helsinki
1Gbps line (option for 10Gbps if load increases)
2TB NVME (option to expand to 8TB if load increases)
Server uses 100% Renewable Energy - 50% Wind 50% Hydro power
https://www.hetzner.com/assets/Uploads/Oomi-sertifikaatti-tuuli+vesi-Hetzner-2021.pdf
Tests
```
#HTTPS
#IPFS
curl https://ipfs.zod.tv/ipfs/QmejvEPop4D7YUadeGqYWmZxHhLc4JBUCzJJHWMzdcMe2y
ipfs
#IPNS
curl https://ipfs.zod.tv/ipns/en.wikipedia-on-ipfs.org/wiki/Architecture | grep jsConfig
<script src="../-/mw/jsConfigVars.js"></script>
#HTTP
#IPFS
curl http://ipfs.zod.tv/ipfs/QmejvEPop4D7YUadeGqYWmZxHhLc4JBUCzJJHWMzdcMe2y
ipfs
#IPNS
curl http://ipfs.zod.tv/ipns/en.wikipedia-on-ipfs.org/wiki/Architecture | grep jsConfig
<script src="../-/mw/jsConfigVars.js"></script>
```
=> feat: add ipfs.zod.tv

src/gateways.json
Jupiter v3.0. Node is currently in datacenter in NE US, multi gbps connection. Available space is currently 10GB @ 90% GC threshold.
=> feat: add gravity.jup.io

src/gateways.json
=> 2read.net does not provide public gateway anymore

package-lock.json, package.json
This is a follow up to https://github.com/ipfs/aegir/pull/944.
I bumped the version and ran `npm install`.
=> chore(deps): bump aegir from 36.1.3 to 36.2.3

src/gateways.json
Added 1 new public gateway server.
https://ipfs.litnet.work
server geolocation - Mumbai, INDIA. :india:
SSL - strict https
connection speed - 2 gbps (upgrade proposed to 4 gbps)
available space - 60 GB
Access - Read only (at this moment)
=> feat: add ipfs.litnet.work

src/gateways.json
[Infura is deprecating the public gateway](https://blog.infura.io/post/introducing-ipfs-dedicated-gateways#deprecation-of-the-public-api-and-gateway) and returning:
```
HTTP/1.1 400 Bad Request
Content-Length: 68
Content-Type: text/plain; charset=utf-8
Date: Fri, 12 Aug 2022 11:35:28 GMT
Vary: Origin
X-Content-Type-Options: nosniff
X-Robots-Tag: noindex
Public Gateway Is Not Supported Anymore - Setup a Dedicated Gateway
```
Probably time to remove it from the list
=> Remove Infura

src/Trustless.ts, src/index.html
Follow up to #310.
In this PR:
- Adding failed to tests to the debug messages.
=> (fix): Follow Up to 310 - Adding more details to failed trustless test

src/Ipns.ts
This fixes test added in https://github.com/ipfs/public-gateway-checker/pull/313 when ipfs-companion is installed and redirect is active.
=> fix: do not redirect IPNS checks

src/gateways.json
The public gateway is located in Portugal, and it is also being used to assist on measurements conducted in collaboration with the PL Probe Lab.
=> feat: add https://ipfs.joaoleitao.org

src/gateways.json
Reverts ipfs/public-gateway-checker#326
Turns out someone loaded a phishing form and reported the site for phishing to google, this is now blocking public gateway checker from testing everything. The cid that's problematic is: `QmaMMPbpjEBqQMfksDTrto1usRpNat9xL6J6ocJ7YNSz3k`
I am not sure what's the best way to block certain routes, is this functionality not built into kubo?
=> Revert "feat: add ipfs.pinksheep.whizzzkid.dev"

src/index.html, src/styles.css
We were using heart to indicate which gateways support Origin isolation, but since then we've added more  tests and the meaning behind heart is lost.
This PR removes :green_heart:  to reduce noise: it should not distract from columns on the left.
=> fix: remove heart

src/gateways.json
This PR removes mrh.io from the list as I'm not currently maintaining an IPFS gateway.
=> chore: removing my gateway for now

package-lock.json, package.json, src/countly.d.ts, src/global.d.ts, src/index.html, src/index.ts, src/metrics.ts, src/styles.css, tsconfig.json
Threw together a quick banner and some logic
=> feat: add countly metrics

src/index.html, src/styles.css
Fixes #341 and addresses #340 
- Moved cookie toggle button to lower left
- Updated metric consent prompt to be fixed at bottom of page
- Updated styles of metric consent prompt (interim fix until new modal updates are added in #340)
https://user-images.githubusercontent.com/10619673/208559656-0ffbd34a-c5d3-4ed4-82bf-149696d4ba54.mov
=> fix: metrics consent prompt location and styling

package-lock.json, package.json, scripts/build-sw.mjs, src/index.html, src/index.ts
Closes: #195 
In this PR:
- Introducing SW to pre-cache assets and also cache assets on the fly.
- The service worker updates every 24-hours and pulls the new manifest, which updates cached files.
- The manifest looks like:
```js
[
{ url:"index.min.js", revision:"dda270ba6f0777cfb842b040c734639d" }, 
{ url:"styles.css", revision:"b77e052ef78550f281b7d16099d69aa4" }
]
```
Screenshots:
- SW Registered
- SW Cache
- SW File Cached
- SW responses cached network first
Future Potential:
- Introduce webmanifest to register gateway checker as a PWA, which can make it installable.
=> feat: Introducing Service Worker For Cache Busting

src/gateways.json
feat: add ipfs.czip.it
location: Italy
av. space: 5 GB
=> Added https://ipfs.czip.it public gateway

src/gateways.json
Soul is a new platform for censorship-resistant blogging. Each article is posted on the IPFS network (or at least pinned locally).
This IPFS instance is hosted on a Vultr VPS based in New Jersey, United States. Current available space is set to 80GB but I definitely plan on scaling in the future if demand increases.
=> feat: add ipfs.soul-network.com

src/gateways.json
Reverts: #323
Closes: #392
Looks like the gateway checker is showing the red-screen from google deceptive check. Just wondering if there's a long-term fix for this 🤔.
=> fix: :rewind: Reverting #323: ipfs.joaoleitao.org

src/gateways.json
Removed https://ipfs.czip.it because it's not working anymore (too much abuse reports from host).
=> feat: Deleted https://ipfs.czip.it

src/gateways.json
while c4rex.co is included as a gateway to check, chrome's red page of death fires on https://ipfs.github.io/public-gateway-checker/ when a network request is sent to c4rex.co to check its status
=> remove the c4rex.co gateway as its currently flagged as unsafe in chrome

src/gateways.json
In a recent meeting with Stef from the Filecoin Foundation, we were advised to rebrand our gateway for improved visibility in the IPFS ecosystem. Therefore, we've changed our gateway from https://starbase.gw3.io to the more straightforward https://gw3.io.
Please review this change in our PR. Looking forward to your feedback.
=> feat: rename starbase.gw3.io to gw3.io

package-lock.json, package.json, src/CheckBase.ts, src/Checker.ts, src/Cors.ts, src/Flag.ts, src/GatewayNode.ts, src/Ipns.ts, src/Origin.ts, src/Stats.ts, src/Status.ts, src/Tag.ts, src/Trustless.ts, src/UiComponent.ts, src/checkViaImgSrc.ts, src/expectSubdomainRedirect.ts, src/global.d.ts, src/index.ts, src/types.ts
* Update eslint-config-ipfs.
* Moved app-specific types to types.ts from global.d.ts due to import() type eslint rule violations.
* add type imports where types are needed and used to be globally available.
=> chore: update eslint-config-ipfs and fix lint

package-lock.json, src/gateways.ts
Closes: #433 
CC: @SgtPooki @BigLep 
This doesn't feel sustainable, maybe the need is to evangelize https://badbits.dwebops.pub/ more.
=> fix(gateways): Removing Offending Gateways

src/gateways.ts
Added twdragon.net to the list of public gateways.
**NOTE**: The gateway supports only subdomain addressing, the case-sensitive path-based CID addressing is blocked programmatically.
=> feat: twdragon.net

gateways.txt
Due to an abuse request from the American Association of Book Publishers, I should delist my experimental gateway and make it private.
=> Delisting twdragon.net

src/gateways.ts
I disabled it years ago due to overuse for the small server powering it and all requests on /ipfs/ and /ipns/ will give 404 HTTP errors so having it advertised here or anywhere else is not useful – logs show that people still try to use it even though it doesn’t work.
=> fix: Drop my long since disabled gateway from your list

gateways.json
This should be the last clean up PR:
- `gateway.ipfs.io` is the same as `ipfs.io` (the DNS records resolve to the same IP). There's no benefit in having both
- `permaweb.eu.org` redirects to `ipfs.io` 
- re-add `hardbin.com` (see https://github.com/ipfs/public-gateway-checker/pull/532#issuecomment-1961931034)
```
http https://permaweb.eu.org/ipfs/bafybeicklkqcnlvtiscr2hzkubjwnwjinvskffn4xorqeduft3wq7vm5u4
HTTP/1.1 302 Moved Temporarily
CF-RAY: 85bfefa45e884294-EWR
Cache-Control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection: keep-alive
Date: Tue, 27 Feb 2024 11:02:32 GMT
Expires: Thu, 01 Jan 1970 00:00:01 GMT
Location: https://ipfs.io/ipfs/bafybeicklkqcnlvtiscr2hzkubjwnwjinvskffn4xorqeduft3wq7vm5u4
NEL: …
```
=> remove duplicate gateways and re-add working one

gateways.json
The gateway was removed from the list, because of some issues/bots making the gateway not respond.
Most issues should be fixed for now as the gateway is online and working fine again.
In the readme.md it says "Add the gateway's address to the top of the list", so therefore I added it to the top.
=> feat: add storry.tv

gateways.json
CloudFlare has deprecated the public IPFS gateways.
=> chore: Delist CloudFlare's gateways due to their discontinuation.

gateways.json
This is a well-connected server in Nürnberg Germany. Free bandwidth limited based on usage; faster paid access will be added later this year.
=> feat: add ipfs.cyou

gateways.json
Deceptive site detected, forced to delist temporarily while fixing this problem. Maybe later it will be published again with a new domain. Sorry if it's a hassle in this very short period of time (not even a month)
=> fix: remove dwt.my.id

gateways.json
Adding EcoLATAM's IPFS Gateway
- Gateway: https://ipfs.ecolatam.com
- Space: 100 GB
- RAM: 3 GB
- Connection Speed: 2 Gbps upload / 1.5 Gbps download
- Location: Hostinger (Europe, exact DC unknown)
This gateway is publicly accessible and intended to support IPFS users in Latin America and globally.
=> add ipfs.ecolatam.com
